### ISSUE TITLE
calla group of items

### ISSUE THREAD

**Issue by StephanKrauss** [sikker/notnosql#1]
Hello,

i look for a simple store.
In the moment i test 'not-nosql'.
Here a simple example:

// PDO
$pdo = new \PDO("mysql:host=".$zugangswerteDatenbankMySQL['hostname'].";dbname=".$zugangswerteDatenbankMySQL['database'],$zugangswerteDatenbankMySQL['username'],$zugangswerteDatenbankMySQL['password']);

```
      // NotNoSQL
        $notNoSql = new \tools\notNoSql($pdo);

        // Test NotNoSql
        $programme100 = array(
            '100' => array(
                'name' => array(
                    'deutsch' => 'deutscher Name 100',
                    'englisch' => 'englischer Name 100'
                ),
                'beschreibung' => array(
                    'deutsch' => 'Beschreibung deutsch 100',
                    'englisch' => 'Beschreibung englich 100'
                )
            )
        );

        $programme200 = array(
            '200' => array(
                'name' => array(
                    'deutsch' => 'deutscher Name 200',
                    'englisch' => 'englischer Name 200'
                ),
                'beschreibung' => array(
                    'deutsch' => 'Beschreibung deutsch 200',
                    'englisch' => 'Beschreibung englich 200'
                )
            )
        );

        $notNoSql->put('bla.12345.programme.100', $programme100);
        $notNoSql->put('bla.12345.programme.200', $programme200);
```

And here my question !
Can i use wildcards in the 'get' command ?

For example:
$test = $this->notNoSql->get('bla.12345.programme.*');

Sorry for my bad english.

Your sincerly

Stephan

**Comment by sikker** [comment]
I decided to revisit this project after a few years and in case anyone cares, this feature is now available.

Simply call $notnosql->get('bla.12345.programme'); to get every programme as an array.'
